# Generated by Django 5.0.4 on 2024-06-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Com_ID', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('House_No', models.AutoField(primary_key=True, serialize=False)),
                ('Woreda', models.CharField(max_length=15)),
                ('Region', models.CharField(max_length=15)),
                ('House_type', models.CharField(max_length=15)),
                ('Family_size', models.CharField(max_length=15)),
                ('Family_names', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('PI_ID', models.AutoField(primary_key=True, serialize=False)),
                ('F_Name', models.CharField(max_length=15)),
                ('M_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('Mother_Name', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Dob', models.DateField()),
                ('Place_of_birth', models.CharField(max_length=15)),
                ('Date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('Nationality', models.CharField(max_length=15)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('Phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('ID_No', models.AutoField(primary_key=True, serialize=False)),
                ('Given_date', models.DateTimeField(auto_now_add=True)),
                ('Expire_date', models.DateField()),
                ('Emergency_cont_name', models.CharField(max_length=15)),
                ('Emergency_cont_number', models.CharField(max_length=15)),
                ('Blood_Type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('AB', 'AB'), ('O+', 'O+'), ('O-', 'O-')], default=None, max_length=2)),
                ('House_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.house')),
                ('PI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('MAR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Given_date', models.DateTimeField(auto_now_add=True)),
                ('witness_1', models.CharField(max_length=15)),
                ('witness_2', models.CharField(max_length=15)),
                ('ID_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.idcard')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='PI_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personalinformation'),
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('Certi_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Given_date', models.DateField()),
                ('House_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.house')),
                ('Father_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_info', to='myapp.personalinformation')),
                ('Mother_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_info', to='myapp.personalinformation')),
                ('PI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='myapp.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('PI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('PI_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personalinformation')),
            ],
        ),
    ]
