# Generated by Django 5.0.4 on 2024-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='Blood_Type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('AB', 'AB'), ('O+', 'O+'), ('O-', 'O-')], max_length=2),
        ),
    ]
