# Generated by Django 5.0.4 on 2024-06-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_idcard_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='PI_ID',
        ),
    ]
